apiVersion: v1
kind: Namespace
metadata:
  name: dbic

#catalogdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogdb
  namespace: dbic
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: dbic
      app.kubernetes.io/name: catalogdb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: catalogdb
        app.kubernetes.io/version: "1"
        app.kubernetes.io/component: service
        app.kubernetes.io/part-of: dbic
        app.kubernetes.io/created-by: suchcodewow
      annotations:
        owner: Database Team
        chat-channel: dev-team-services
    spec:
      containers:
        - name: catalogdb
          image: mysql
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
              name: catalogdb
          env:
            - name: DT_CUSTOM_PROP
              value: "project=dbic service=catalogdb"
            - name: MYSQL_USER
              value: api
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: catalogDb

---
apiVersion: v1
kind: Service
metadata:
  name: catalogdb
  namespace: dbic
  labels:
    app.kubernetes.io/part-of: dbic
    app.kubernetes.io/name: catalogdb
spec:
  ports:
    - port: 3306
      targetPort: 3306
      name: catalogdb
  selector:
    app.kubernetes.io/part-of: dbic
    app.kubernetes.io/name: catalogdb
  type: ClusterIP

#catalogAPI
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogapi
  namespace: dbic
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: dbic
      app.kubernetes.io/name: catalogapi
  template:
    metadata:
      labels:
        app.kubernetes.io/name: catalogapi
        app.kubernetes.io/version: "1"
        app.kubernetes.io/component: service
        app.kubernetes.io/part-of: dbic
        app.kubernetes.io/created-by: suchcodewow
      annotations:
        owner: Services Team
        chat-channel: dev-team-services
    spec:
      containers:
        - name: catalogapi
          image: suchcodewow/dbic-catalogapi:ccare
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: catalogapi
          env:
            - name: DT_CUSTOM_PROP
              value: "project=dbic service=catalogapi"

---
apiVersion: v1
kind: Service
metadata:
  name: catalogapi
  namespace: dbic
  labels:
    app.kubernetes.io/part-of: dbic
    app.kubernetes.io/name: catalogapi
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: catalogapi
  selector:
    app.kubernetes.io/part-of: dbic
    app.kubernetes.io/name: catalogapi
  type: LoadBalancer
