pipeline:
  identifier: Build_suchcodewow_catalogapi_1710077249737
  name: Build catalogapi
  orgIdentifier: default
  projectIdentifier: catalogapi
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1709938520408
        repoName: suchcodewow/catalogapi
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  identifier: Build_and_push_to_Docker
                  name: Build and push to Docker
                  spec:
                    connectorRef: account.harnessImage
                    repo: suchcodewow/catalogapi
                    tags:
                      - <+pipeline.sequenceId>
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
